name: Build and Publish Sail Image

on:
  push:
    branches: [main]
    tags: ["v*"]
  schedule:
    - cron: "30 1 * * 4" # Every Thursday at 1:30 UTC (7:00 AM IST)
    - cron: "30 1 * * 1" # Every Monday at 1:30 UTC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with Sail
        run: ./vendor/bin/sail build

      - name: Tag and Push Image
        run: |
          IMAGE_NAME=ghcr.io/clarity-tech/laravel-essentials-starter-kit
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag laravel.test $IMAGE_NAME:${{ github.sha }}
            docker push $IMAGE_NAME:${{ github.sha }}
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            docker tag laravel.test $IMAGE_NAME:$VERSION
            docker tag laravel.test $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$VERSION
            docker push $IMAGE_NAME:latest
          fi
